/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proyecto1;

import com.mycompany.proyecto1.Repositorys.ClientesRepo;
import com.mycompany.proyecto1.services.ServicioCliente;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Service;

import java.awt.event.ItemEvent;
import javax.swing.JFrame;

/**
 *
 * @author casa
 */
//@Component
public class MenuGUI extends javax.swing.JFrame {
    private Creacion creacion;

    private OrdenCompraGUI orden;
    private OrdenVenta venta;
    private Produccion produccion;
    private Importacion importacion;
    private Facturacion facturacion;

    /**
     * Creates new form MenuGUI
     */
    public MenuGUI() {
        initComponents();
    }

    public MenuGUI(Creacion creacion) {
        this.creacion = creacion;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccione aquí", "orden de compra", "orden de venta", "produccion", "importacion", "facturacion" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 935, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(414, 414, 414)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(414, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(325, 325, 325)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(326, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED && evt.getSource() == jComboBox1) {
            // Obtener el valor seleccionado
            String selectedItem = (String) evt.getItem();
            if (selectedItem.equalsIgnoreCase("orden de compra")) {
                if (orden == null || !orden.isVisible()) {
                    orden = new OrdenCompraGUI(this.creacion);
                    orden.setVisible(true);
                } else {
                    orden.toFront();
                    orden.requestFocus();
                }
                orden.setVisible(true);
                orden.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            } else if (selectedItem.equalsIgnoreCase("orden de venta")) {
                if (venta == null || !venta.isVisible()) {
                    venta = new OrdenVenta(this.creacion);
                    venta.setVisible(true);
                } else {
                    venta.toFront();
                    venta.requestFocus();
                }
                venta.setVisible(true);
                venta.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            } else if (selectedItem.equalsIgnoreCase("produccion")) {
                if (produccion == null || !produccion.isVisible()) {
                    produccion = new Produccion(this.creacion);
                    produccion.setVisible(true);
                } else {
                    produccion.toFront();
                    produccion.requestFocus();
                }
                produccion.setVisible(true);
                produccion.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            } else if (selectedItem.equalsIgnoreCase("importacion")) {
                if (importacion == null || !importacion.isVisible()) {
                    importacion = new Importacion();
                    importacion.setVisible(true);
                } else {
                    importacion.toFront();
                    importacion.requestFocus();
                }
                importacion.setVisible(true);
                importacion.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            } else if (selectedItem.equalsIgnoreCase("facturacion")) {
                if (facturacion == null || !facturacion.isVisible()) {
                    facturacion = new Facturacion(this.creacion);
                    facturacion.setVisible(true);
                } else {
                    facturacion.toFront();
                    facturacion.requestFocus();
                }
                facturacion.setVisible(true);
                facturacion.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            }
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables
}
